use_frameworks!

platform :ios, '8.0'

target 'MPmetiator_Example' do
  pod 'MPmetiator', :path => '../'

  target 'MPmetiator_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
